name: posts
description: Posts module.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ## infrastructure
  common_dependencies:
    path: ../../infrastructure/common_dependencies/
  core:
    path: ../../infrastructure/core/
  shared_presentation:
    path: ../../infrastructure/shared_presentation/
  shared_data:
    path: ../../infrastructure/shared_data/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
    - assets/subtitles/



